### ISSUE TITLE
Add feature to replace the image tag flux automation controller imagepolicy

### ISSUE THREAD

**Issue by simongottschlag** [XenitAB/azcagit#28]
Feature should look something like this:

```yaml
kind: AzureContainerApp
apiVersion: aca.xenit.io/v1alpha1
metadata:
  name: foobar
spec:
  replacements:
    images:
      - imageName: "mcr.microsoft.com/azuredocs/containerapps-helloworld"
        newImageTag: "v0.1" # {"$imagepolicy": "apps:podinfo:tag"}
  app:
      template:
        containers:
          - name: simple-hello-world-container
            image: mcr.microsoft.com/azuredocs/containerapps-helloworld:latest
```

When the tag is updated, it should become the following image in Azure Container Apps: `mcr.microsoft.com/azuredocs/containerapps-helloworld:v0.1`
